name: swipe_stack
description: Flutter swipe stack widget.
version: 1.0.0
author: G.Mete Korkmaz <g.metekorkmaz@gmail.com>
homepage: https://github.com/gmetekorkmaz/SwipeStack

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter